# Generated by Django 4.2.1 on 2023-06-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alios',
        ),
    ]
